apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: vmauth-sample
spec:
  userSelector: {}
  userNamespaceSelector: {}
  replicaCount: 1
  resources:
    requests:
      cpu: "250m"
      memory: "350Mi"
    limits:
      cpu: "500m"
      memory: "850Mi"
  unauthorizedAccessConfig:
    - src_paths:
        - /*
      url_prefix:
        - http://vmsingle:8429/
        - http://vmsingle-2:8429/
      ip_filters:
        allow_list:
          - 127.0.0.1
          - 192.168.0.0/16
        deny_list:
          - 10.0.0.0/8
